### ISSUE TITLE
GPS location varying widely

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#11]
In autonomous mode, LCR wanders excessively, apparently following large GPS location variations. Initially thought this was due to limited view of the sky, but moved to a test an area with fairly clear sky, and still seeing location shifts which cause Percy to reorient and make large deviations from the intended work area.
![image](https://user-images.githubusercontent.com/84051775/124796520-1c264500-df06-11eb-919d-6781f42e60de.png)

**Comment by georgechrysanthakopoulos** [comment]
@abtinling I noticed this too from telemetry but I needed "ground truth" confirmation.
Lets do a remote autonomous session: I will connect remotely, while you watch it, then we can see what is going on. The wandering is sometimes due to GPS, most often is due to obstacles. If you disable physical obstacle avoidance within that area, and try again, it will tell us which is which. Please follow up on email to schedule a remote autonomous session

**Comment by georgechrysanthakopoulos** [comment]
there is no GPS antenna issue and with obstacle avoidance off, as long as the robot is away from trees, location seems stable. Unfortunately, there is no tru open southern sky in the areas we tried. Best I can tell, this is environmental. Happy to do more remote autonomy sessions at any time
