### ISSUE TITLE
Mower angle adjustment turnbuckle loosening while running

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#17]
The top-link turnbuckle which adjusts the angle of the mower deck was loosening up while the mower was operating, so that the deck was sagging at the far side. I drilled a hole in the turnbuckle screw and inserted a locking pin so it maintains adjustment.

![image](https://user-images.githubusercontent.com/84051775/126237811-8adaf5ee-d0b0-4046-9d84-7d24f1b4e7b5.png)

**Comment by georgechrysanthakopoulos** [comment]
Clever. Not sure why we are not seeing this in other LCRs (or at least nobody is telling us?) with 100+ miles on them.
I will go ahead and change our build instructions to insert a hex lock nut, at end of rod, to achieve the same thing, but without drilling. Thanks again!

**Comment by georgechrysanthakopoulos** [comment]
well lock nut, even thin profile might not fit, drilling might be the only option :(

**Comment by abtinling** [comment]
My old Kubota tractor had some 3pt hitch anti-sway turnbuckles which gave me the idea for the pin. Kinda like these: https://www.amazon.com/Universal-Stabilizer-Turnbuckle-Replaces-Tractors/dp/B07QYWPJF5

**Comment by georgechrysanthakopoulos** [comment]
https://photos.app.goo.gl/sEzXRF62AYaHkXo1A

The fix requires 1x 1/2"-13 Nylon-Insert Locknut.

Note the orientation of the turnbuckle. There is an "L" on one side of the turnbuckle, and an "R" on the other side.
Twist to remove the turnbuckle while holding the end rods still, separating the assembly into three pieces; the right threaded rod, the left threaded rod, and the center.
Thread the nut onto the right threaded rod, and tighten it until it sits around 3" from the open end of the rod. The left rod is reverse threaded, so the nut will not thread onto that rod.
Replace the center, connecting the two rods to their respective ends of the center. Twist to combine.
Adjust both the turnbuckle so that the mower sits flush with the ground, or to the desired angle.
Tighten the nut against the turnbuckle, so that the nut sits flush to the "R" end of the center piece.
Tighten well.
The nut keeps tension on the turnbuckle center, thus providing resistance against twisting or vibration.

**Comment by georgechrysanthakopoulos** [comment]
thanks again for the report, see resolution above (using just a locknut, which we will install on mowers going forward).
