### ISSUE TITLE
Work Area GPS wandering, possible bias in one direction

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#21]
Carefully marked a rectangle on the ground today, and precisely drove LCR around the perimeter. Made a plan corresponding as closely as possible to the track. While running the plan Percy seemed to some persistent bias, cutting the Southwest corner, and hugging the South side of the work area. It seemed to be doing something similar while testing with wide open sky on my neighbor's property a couple weeks ago. 
![image](https://user-images.githubusercontent.com/84051775/139513507-758965c5-4283-4d98-a711-f767aafa6a9d.png)
![image](https://user-images.githubusercontent.com/84051775/139513689-da3a977c-2a72-487b-be9b-ed9a408ba1d8.png)
![image](https://user-images.githubusercontent.com/84051775/139513713-cb069746-f1a4-430b-a6b9-c1d11093d1f7.png)

**Comment by georgechrysanthakopoulos** [comment]
Thank you for the report!

 Our area planner will avoid making sharp turns to minimize in place rotations. As we approach a vertex we take many factors into account: task speed, obstacles, polygon shape. We also use real time GPS DOP (dilution of precision).
The worse the estimated accuracy, the sooner we turn :)
Indeed, if you look at the time series for the positional accuracy, in meters (its a rough estimate, 0.6 is great with regular GPS, 0.9 or more, not great), the worst precision is on the south side due to the tall trees.
see the attached screenshots.
We are working in integrating over the air RTK corrections, with our robots, we will let you know when its ready to try: it will not require a base station installed. It *might* help in the open area above. We also have working UWB RTLS (local positioning with anchors and a tag on the robot), but not ready for deployment

<img width="655" alt="Screen Shot 2021-10-29 at 7 52 56 PM" src="https://user-images.githubusercontent.com/978440/139517918-5d734ff8-f226-4a19-80b6-fd2f57af0990.png">
<img width="664" alt="Screen Shot 2021-10-29 at 7 52 38 PM" src="https://user-images.githubusercontent.com/978440/139517920-5715107c-8196-43e3-a3df-486e364df0d5.png">
<img width="544" alt="Screen Shot 2021-10-29 at 7 53 17 PM" src="https://user-images.githubusercontent.com/978440/139517916-704316b1-164b-4340-a150-65cf3f5e51a9.png">

**Comment by georgechrysanthakopoulos** [comment]
We do lots of area coverage weekly, but i just confirmed, at Whidbey island, with a challenging shape, that if the GPS performance is good, we do the tight turns as expected, this is from just now, at the farm we met originally for the LCR demo :) We believe we have a way to improve precision in hard (for GPS) areas, like yours, very soon. More on that on email
![Screen Shot 2021-10-30 at 3 07 16 PM](https://user-images.githubusercontent.com/978440/139559648-f7d6007b-e8f1-4e32-825f-13c03f08bef2.png)
![Screen Shot 2021-10-30 at 3 05 53 PM](https://user-images.githubusercontent.com/978440/139559649-1a5c9be0-d15e-43cb-a2fa-e1682616c6f7.png)
.
