### ISSUE TITLE
Workarea / Plan only on LCR phone - Not on laptop

### ISSUE THREAD

**Issue by gatesl** [directedmachines/customer-support#24]
For my LCR when I log in from a laptop to edit a plan, there is only a default plan.  From the LCR phone all of the plans from last year are present.  How can I get the laptop to have the plans so I can edit them? This appears to be a regression from last fall.

**Comment by georgechrysanthakopoulos** [comment]
@gatesl your plans are now on your fleet page as well. Due to same data changes, they had to get re-exported.

Tons of software changes, FYI, tutorials a bit behind. Basics still about the same.
We have a new high precision package for both GPS and IMU but there is an up charge, again, FYI.

![Screen Shot 2022-05-23 at 8 25 04 PM](https://user-images.githubusercontent.com/978440/169942887-2a7e337b-2e61-4538-b128-bfe283f5c933.png)
