### ISSUE TITLE
Battery Management System- Fluctuating readings

### ISSUE THREAD

**Issue by DeanKoyanagi** [directedmachines/customer-support#5]
At 11:53 am (Eastern)- While working on identifying the latest gear noise I disengaged the power to the motors. Power was in the low 90s when I inserted the fuse. LCR is hooked up to the solar panels which are mounted outside the barn during repairs. When I restored power to the motors for a higher speed test (manually spinning the gears for most testing) there was a LOW POWER warning at 3%. While I watched it rose to 6, then jumped to 11%, the phone disconnected while I wasn't touching anything and rebooted. When it came back on, and I reconnected the phone, it showed 96%.  No power or communications lined appear loose although the wheel camera ,ePTO, and lift are disconnected and removed for better access to the drive box.  I continued working on the gear noise. At 12:24 it dropped to 29% when I disengaged the power disconnect to remove the whole drive gearbox again.

**Comment by georgechrysanthakopoulos** [comment]
@DeanKoyanagi That was all because of me: False Alarm. I rebooted your robot thinking it was reproducing an SCC board issue. Also our current state of charge tracking is all in memory, last 3 hours. If we reboot, we loose all that, so report garbage. Under normal load, its accurate. Also note , we have an electronics/ current shunt based coulomb counter FW+circuit that will replace the SW estimation soon

**Comment by georgechrysanthakopoulos** [comment]
this has been resolved. it will improve further once we have AC charging current visibility
