### ISSUE TITLE
Loss of Navigation Page following reinstallation of cameras, GPS, and LTE antenna

### ISSUE THREAD

**Issue by DeanKoyanagi** [directedmachines/customer-support#9]
After installing the new motors and reduction drives, I tested and adjusted the chains several times using the manual driving with no cameras or LTE antenna connected. When I felt the chain drives were properly adusted I intalled the Caster camera, as well as the  GPS and LTE antennas. Camera was working and the LCR's location were updated and visible on the phone when logging in. I drove the LCR about 15ft out of the barn and parked it in a sunny spot to fully recharge.
When I went to drive it later (to test the follow mode with a red LED light) the WiFi wasn't visible. Rebooted and the WiFi was visible, but when going to the Navigation Page, I now get the following message:

{"message":"Service not found: http://127.0.0.1:8000/actuators/navigators/default/ui","statusCode":404,"documentKind":"com:dcentralized:core:common:ServiceErrorResponse","errorCode":-2147483648}"

I disconnected the camera, GPS, and LTE, but still I'm getting the same message.

**Comment by georgechrysanthakopoulos** [comment]
The Manual Control UI did not use to load when the motor controller did not enumerate (it does now, gives a "Electric Drive Enumeration" error).
The motor controllers are not enumerating because the HubHAT (Small USB  connector + sensor board on top of your Raspberry PI4) appears to have been electrically damaged: no peripherals connected to it will be visible to our SW.

What likely happened was that antenna SMA connectors, OR, Camera casings touched the frame, when you were re wiring. If there was static build up up, a ESD event likely occurred, or, a  ground loop was created between chassis and USB ground.

I am sending you new Pi + RadioHAT + 3D Printed solar panel mounts + USB Hub which will bring your robot to latest "fleet" normal, but will require you to mount the PI+Hat+3D print using either a zip tie, or custom holes + bolts, so its oriented properly. You must be careful when doing the re wiring, keep all usb connectors and antennas isolated from frame/tray (use electrical tape).

we have an old B3 that we still keep running, here is an image of the Pi+HAT mounted with new print, in an old electronics tray, similar to yours, so you have an idea of orientation

**Comment by georgechrysanthakopoulos** [comment]
![IMG_4964](https://user-images.githubusercontent.com/978440/117708552-cdb62d80-b184-11eb-9ece-fc57e27d491f.jpg)

**Comment by georgechrysanthakopoulos** [comment]
cables have been labeled, F.C means front/axle side camera, B.C means back/caster side camera. I am hoping cameras are ok, these are expensive to replace.

Standard wiring images:
https://user-images.githubusercontent.com/978440/113954680-2afa4000-97cf-11eb-8529-542489e267e6.jpg

https://user-images.githubusercontent.com/978440/113955890-6dbd1780-97d1-11eb-9774-0fae85e1d7d8.png

![IMG_4966](https://user-images.githubusercontent.com/978440/117713472-8f237180-b18a-11eb-958c-91d5c2f07a58.jpg)

**Comment by DeanKoyanagi** [comment]
Over the weekend, the USB adapters I ordered came in, and I connected all the wires to the USB 3.0 Hub and Pi+Radio Hat as directed. I inserted the fuse and at least the WiFi booted right up. In the navigation screen, I now only get a red Electric Drive Enumeration Fault message. 

Also, you have "PICO" identified as a USB port on the images you sent, I'm assuming that goes to the 12V lift? No references to PICO in the other documentation I have, and nothing in these photos with LIFT identified as in earlier photos.

Unfortunately, as you feared, the short did damage the Realsense camera that I had connected. I installed Intel's RS Camera app on the Samsung Active Tab 3 I bought for being able to adjust autonomous areas while in the field. The camera (Axle Cam #2)  that had been disconnected, works when I plug it into the tablet, but it doesn't show any image when connected to the LCR and viewing the navigation screen set to that direction. All I get is the Electric Drive Enumeration Fault message. I rebooted the LCR, but with no apparent changes.

Also, it appears that there are no lights at all on the second LTE...looks like that got fried too. Before I order a new D435 camera (if that's still the recommended model) and LTE, do you have documentation or recommendations for additional steps for diagnosing the Telenor LTE? I didn't see anything in a cursory search. Or should I just order one of those as well?

What do you think about me intalling the main electronics in a poly case with ports for wires, cut outs in the bottom for the heat sinks and a fan with additional vents? What would you recommend for additional grounding points? I was thinking something akin to [this](https://www.bhphotovideo.com/c/product/1225115-REG/skb_3i_3424_12be_iseries_waterproof_utility_case.html/specs?ap=y&ap=y&smp=y&smp=y&lsft=BI%3A514&gclid=CjwKCAjwv_iEBhASEiwARoemvMPIHj6r2iZyX0ZQB7Z3UmtHB2GXIxO7IltqW8JmbeyDAQYjyJ8cnBoC7kYQAvD_BwE)? It would cover the battery bank, leaving access to the reduction components and motors.

Also, after the incident with the loose positive wire to the DC/AC invertor (shared in google photos) do you have concerns if I install an emergancy battery disconnect like the Albright [ED250](https://www.curtisinstruments.com/products/dc-contactors/#) I have from a past project. I know you have designed the LCR to have power to certain functions all the time,  but not being able to quickly disconnect the batteries in an emergency seems like a risk.

**Comment by georgechrysanthakopoulos** [comment]
@DeanKoyanagi I believe you have some extra LTE modems from previous iterations. If not, I will send you one. I can also send a new camera, free of charge. Please email me if you can not find a modem. I think the next step, before you make any more changes is to get the LTE modem (that I send you, or you have) connected, so I can remotely connect and triage.
The LCR can operate with one camera, one in the direction of motion (for example, if you go caster first, that camera needs to work)
Please note we do have an emergency shutoff to batteries in all trays build since November 2020. A 350A anderson with 4/0 cable blades (rated for 1000A) that can be removed from tray. Plus, the main MC -> battery rotary switch. you can install a 350A anderson tail, crimp to battery side, then another 350A anderson tail from bus bar and ground inside tray, like we do these days: 
tray side tail for main supply: https://photos.app.goo.gl/aZYtVhhu2Ewms5GC7

battery side, LCR exterior of tray: https://photos.app.goo.gl/hncku4sgWKpmEMEx9

**Comment by georgechrysanthakopoulos** [comment]
the 12V actuator can be plugged in the PICO port. I will need to log in remotely to configure it, but the actuator should be usable through the manual switch either way.

**Comment by DeanKoyanagi** [comment]
Hi Georgia's,

Good memory! I had forgotten there was an LTE still here from last year.
The LTE I had packed to send back with earlier hats, but forgot to actually
mail it, seems to be working now. Also I am able to see the one good cam is
working now (It is connected to FC port, but showing as axle FWD on the
configuration screen).

I'll leave it as is for now in the barn if the LTR signal is strong enough
for you to do any diagnostics or resetting. As we may get some severe
thunderstorms today and tomorrow and we're trying to transplant everything
we can before the rains come.

Dean

**Comment by georgechrysanthakopoulos** [comment]
as I mentioned on email (and seen in our fleet view) the robot is driving and reporting telemetry fine (when outside barn) with new USB topology. RealSense replacement camera has been ordered and coming from Amazon directly.
